SECRET_KEY: '123qwe'  # 任意字符串

# 数据库信息
db:
  host: ''
  port: 3306
  user: ''
  password: ''
  database: ''

# token超时时间，单位为秒
token_time_out: 36000

# 分页信息
page:
  pageNum: 1
  pageSize: 20

# 企业群消息机器人地址，用于接收报告
webhook: ''

# 测试报告前端地址
report_addr: 'http://xx.xx.xx.xx/#/apiTest/report'

# 即时达推送 的 系统错误通道
error_push:
  url: 'http://push.ijingniu.cn/send'
  key: ''

# yapi相关信息，用于同步项目、模块、接口信息
yapi:
  host: 'http://yapi'  # yapi 域名
  account: ''  # yapi的登录账号
  password: ''  # yapi的登录密码
